import { Resume } from "./types/resume";

export const resume: Resume = {
    experiences: [
        {
            company: `Showrunner`,
            link: `https://showrunner.tech/`,
            description: `Built an integrated platform to help studios coordinate and manage their physical and virtual sets.`,
            role: `Senior Fullstack Engineer`,
            startDate: new Date(2023, 1, 1),
            endDate: new Date(2023, 8, 1),
            logoPath: `/showrunner.svg`,
            technologies: [
                `NodeJS`, 
                `Typescript`, `SQL`, `Prisma`, `React`, `NextJS`, `NestJS`, `Apollo`, `GraphQL`, `Unreal`, `GitHub Actions`,
            ],
        },
        {
            company: `IBM`,
            description: `Built an AI platform to help users easily integrate AI into their pipelines with off the shelf solutions.`,
            role: `Senior Fullstack Engineer`,
            startDate: new Date(2021, 6, 1),
            endDate: new Date(2023, 1, 1),
            logoPath: `/ibm.png`,
            technologies: [
                `NodeJS`, `Typescript`, `Postgres`, `gRPC`, `Terraform`, `AWS EC2`, `React`, `Mobx`, `Docker`,
            ],
            team: `ConveyorAI`,
            link: `https://conveyorai.com/`,
        },
        {
            company: `IBM`,
            description: `Lead a team of engineers in building and managing systems that integrated between platforms such as Slack, PagerDuty, and GitHub with internal systems.`,
            role: `Full Stack Engineer and Team Lead`,
            startDate: new Date(2018, 1, 1),
            endDate: new Date(2021, 6, 1),
            logoPath: `/ibm.png`,
            technologies: [
                `Typescript`, `MongoDB`, `Redis`, `Bolt`, `NewRelic`, `LogDNA`, `Docker`, `Kubernetes`, `Watson Assistant`, `SQL Query`, `Cloud Object Storage (COS)`, `React`, `Travis`, `GitHub Actions`, `Artifactory`,
            ],
            team: `Powerups@IBM`,
        },
        {
            company: `IBM`,
            description: `Helped roll out Slack to all of IBM and built out a microservice architecture that deeply integrated with Slack’s APIs. These integrations manage crucial admin tasks such as: offboarding, profile sync, provisioning.`,
            role: `Full Stack Engineer`,
            startDate: new Date(2016, 6, 1),
            endDate: new Date(2018, 1, 1),
            logoPath: `/ibm.png`,
            technologies: [
                `NodeJS`, `RabbitMQ`, `Redis`, `Seneca`, `Botkit`, `Slapp`, `Cloudant`, `Amazon S3`, `Travis`, `Docker`,
            ],
            team: `Slack@IBM`,
        },
        {
            company: `Hudl`,
            description: `Built out features for athlete’s newsfeeds such as reactions and helped make improvements to the Hudl iOS app.`,
            role: `Full Stack Engineer Intern`,
            startDate: new Date(2015, 7, 1),
            endDate: new Date(2016, 6, 1),
            logoPath: `/hudl.png`,
            technologies: [
                `C#`, `.Net`, `CSS`, `React`, `Swift`,
            ],
            team: `Community`,
            link: `https://www.hudl.com/`,
        },
        {
            company: `IBM`,
            description: `Designing and developing a Web interface for IBM executives to aid in the analysis of medical documents and their correlating ranking metrics generated by Watson.`,
            role: `UI/UX Web Developer Intern`,
            startDate: new Date(2015, 4, 1),
            endDate: new Date(2015, 7, 1),
            logoPath: `/ibm.png`,
            technologies: [
                `Java`, `Angular`, `CSS`, `CloudantDB`,
            ],
            team: `Extreme Blue`,
        },
    ],
    education: {
        school: `University of Nebraska - Lincoln`, 
        program: `Jeffrey Raikes School of Computer Science and Business Management`,
        startYear: 2012,
        endYear: 2016,
        degrees: [
            {
                degree: `Bachelors`,
                study: `Computer Science`,
            },
            {
                degree: `Bachelors`,
                study: `Mathematics`,
            },
            {
                degree: `Minor`,
                study: `Business Management`,
            },
        ],
    },
    contact: {
        name: `Shannen Lambdin`,
        location: `Raleigh, NC`,
    },
    skills: [
        `Typescript`,
        `Fullstack`,
        `DevOps`,
        `React.Js`,
        `NodeJS`,
        `IBM Cloud`,
        `AWS`,
    ],
    interests: [],
    tldr: `I'm a heads-down get sh*t done engineer. It doesn't matter where in the stack I work. I take pride in taking a project from ideation to implementation to production.\n\nI enjoy working with designers and product managers to implement the best user experience possible.`,
};